[package]
name = "dunnoconz/shibe-spring"
description = "Basic spring made by BlackShibe"
version = "1.1.2"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = [
  "LICENSE", "README.md"
]